export const SET_TOKEN = "SET_TOKEN";
export const SET_USER_PROFILE = "SET_USER_PROFILE";
export const INIT_SET_USER_PROFILE = "INIT_SET_USER_PROFILE";

export const SET_PRIMARY_COLOR = "SET_PRIMARY_COLOR";
export const SET_CATEGORY_ID_PLAYLISTS = "SET_CATEGORY_ID_PLAYLISTS";

export const SET_CATEGORIES = "SET_CATEGORIES";
export const INIT_SET_CATEGORIES = "INIT_SET_CATEGORIES";

export const INIT_SET_NEW_RELEASES = "INIT_SET_NEW_RELEASES";
export const SET_NEW_RELEASES = "SET_NEW_RELEASES";

export const INIT_SET_FEATURED_PLAYLISTS = "INIT_SET_FEATURED_PLAYLISTS";
export const SET_FEATURED_PLAYLISTS = "SET_FEATURED_PLAYLISTS";

export const SET_SELECTED_GENRE_ID = "SET_SELECTED_GENRE_ID";
export const SET_SELECTED_PLAYLIST_ID = "SET_SELECTED_PLAYLIST_ID";
export const SET_TRACKS = "SET_TRACKS";
export const SET_SELECTED_TRACK_ID = "SET_SELECTED_TRACK_ID";
export const SET_SEARCHED_SONGS = "SET_SEARCHED_SONGS";
export const INIT_SET_TRACKS = "INIT_SET_TRACKS";

export const INIT_SET_ALBUM_TRACKS = "INIT_SET_ALBUM_TRACKS";
export const INIT_SET_PLAYLIST_TRACKS = "INIT_SET_PLAYLIST_TRACKS";

export const INIT_SET_CATEGORY_ID_PLAYLISTS = "INIT_SET_CATEGORY_ID_PLAYLISTS";
export const SET_USER_PLAYLISTS = "SET_USER_PLAYLISTS";
export const INIT_SET_USER_PLAYLISTS = "INIT_SET_USER_PLAYLISTS";

export const INIT_SET_PLAYLIST_DETAIL = "INIT_SET_PLAYLIST_DETAIL";
export const SET_PLAYLIST_DETAIL = "SET_PLAYLIST_DETAIL";

export const INIT_SET_ALBUM_DETAIL = "INIT_SET_ALBUM_DETAIL";
export const SET_ALBUM_DETAIL = "SET_ALBUM_DETAIL";

export const INIT_SET_ARTIST_DETAIL = "INIT_SET_ARTIST_DETAIL";
export const SET_ARTIST_DETAIL = "SET_ARTIST_DETAIL";

export const SET_ARTIST_TOP_TRACKS = 'SET_ARTIST_TOP_TRACKS';
export const INIT_SET_ARTIST_TOP_TRACKS = "INIT_SET_ARTIST_TOP_TRACKS";
export const INIT_SET_FOLLOWING_ARTISTS = "INIT_SET_FOLLOWING_ARTISTS";
export const SET_FOLLOWING_ARTISTS = "SET_FOLLOWING_ARTISTS";

export const INIT_SET_FOLLOWING_PLAYLISTS = "INIT_SET_FOLLOWING_PLAYLISTS";
export const SET_FOLLOWING_PLAYLISTS = "SET_FOLLOWING_PLAYLISTS";

export const INIT_SET_FOLLOWING_ALBUMS = "INIT_SET_FOLLOWING_ALBUMS";
export const SET_FOLLOWING_ALBUMS = "SET_FOLLOWING_ALBUMS";

export const INIT_FOLLOW_ARTIST = "INIT_FOLLOW_ARTIST";
export const INIT_UNFOLLOW_ARTIST = "INIT_UNFOLLOW_ARTIST";
 

export const INIT_FOLLOW_PLAYLIST = "INIT_FOLLOW_PLAYLIST";
export const INIT_UNFOLLOW_PLAYLIST = "INIT_UNFOLLOW_PLAYLIST";
 

export const INIT_FOLLOW_ALBUM = "INIT_FOLLOW_ALBUM";
export const INIT_UNFOLLOW_ALBUM = "INIT_UNFOLLOW_ALBUM";
 
export const SET_SEARCH_TERM = "SET_SEARCH_TERM";
export const INIT_SET_SEARCH_ITEMS = "INIT_SET_SEARCH_ITEMS";
export const SET_SEARCH_ITEMS = "SET_SEARCH_ITEMS";
export const INIT_SET_RECOMMENDATIONS = "INIT_SET_RECOMMENDATIONS";
export const SET_RECOMMENDATIONS = "SET_RECOMMENDATIONS";

export const INIT_SET_ARTIST_ALBUMS = "INIT_SET_ARTIST_ALBUMS";
export const SET_ARTIST_ALBUMS = "SET_ARTIST_ALBUMS";

export const INIT_SET_RELATED_ARTISTS = "INIT_SET_RELATED_ARTISTS";
export const SET_RELATED_ARTISTS = "SET_RELATED_ARTISTS";

export const LOGOUT = "LOGOUT";

export const SET_CURRENT_PLAYING_TRACK_INDEX = "SET_CURRENT_PLAYING_TRACK_INDEX";
export const SET_CURRENT_PLAYING_ID = "SET_CURRENT_PLAYING_ID";

export const INIT_SET_LIKED_TRACKS = "INIT_SET_LIKED_TRACKS";
export const SET_LIKED_TRACKS = "SET_LIKED_TRACKS";
export const CLEAR_FOLLOWING_ARTISTS = "CLEAR_FOLLOWING_ARTISTS";
export const CLEAR_FOLLOWING_PLAYLISTS = "CLEAR_FOLLOWING_PLAYLISTS";
export const CLEAR_FOLLOWING_ALBUMS = "CLEAR_FOLLOWING_ALBUMS";
export const CLEAR_LIKED_TRACKS = "CLEAR_LIKED_TRACKS";
export const RUN_CHECK_FOLLOWING = "RUN_CHECK_FOLLOWING";
export const INIT_SET_RECENTLY_PLAYED = "INIT_SET_RECENTLY_PLAYED";
export const SET_RECENTLY_PLAYED = "SET_RECENTLY_PLAYED";
export const INIT_SET_IS_FOLLOWING = "INIT_SET_IS_FOLLOWING";
export const SET_IS_FOLLOWING = "SET_IS_FOLLOWING";
export const INIT_SET_IS_FOLLOWING_PLAYLIST = "INIT_SET_IS_FOLLOWING_PLAYLIST";
export const INIT_SET_IS_FOLLOWING_ARTIST = "INIT_SET_IS_FOLLOWING_ARTIST";
export const INIT_SET_IS_FOLLOWING_ALBUM = "INIT_SET_IS_FOLLOWING_ALBUM";
export const INIT_FOLLOW_TRACK = "INIT_FOLLOW_TRACK";
export const INIT_UNFOLLOW_TRACK = "INIT_UNFOLLOW_TRACK";
// export const INIT_FOLLOW_TRACK = "INIT_FOLLOW_TRACK";


